### PR TITLE
flutter: fix subscriptions, update dependencies (close #210, #214)

### LINKED ISSUE #210: [Flutter] Subscriptions not working
The queries are OK, but seems like subscriptions have a problem with the authorization with the socket.
In my fork oh this repo have a version of the boilerplate updated to work with the latest version of the graphql_flutter, but can't figure out how to make the subscriptions work.
Someone know what is the problem?

{extensions: {path: $, code: start-failed}, message: cannot start as connection_init failed with : Authentication hook unauthorized this request}

hasura_flutter_tutorial_error

### PR DESCRIPTION
**Pull request by divjakLab**
Update dependency in FlutterApp ( app-final ). Change code to work with new version and update subscription.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -3,3 +3,5 @@
 .vscode
 *.idea
 *node_modules
+
+tutorials/mobile/flutter-graphql/app-final/.packages
```
Comment (praveenweb) [inline .gitignore:7]: Can we add this to the app-final .gitignore instead of being on the parent .gitignore?

File: tutorials/mobile/flutter-graphql/app-final/ios/Flutter/flutter_export_environment.sh [hunk 2]
```diff
@@ -0,0 +1,11 @@
+#!/bin/sh
```
Comment (praveenweb) [inline tutorials/mobile/flutter-graphql/app-final/ios/Flutter/flutter_export_environment.sh:1]: This file shouldn't be in version control. Can you remove this?

File: .gitignore (hunk 1 above)
Comment (divjakLab) [reply .gitignore]: Done
